include: package:flutter_lints/flutter.yaml

# Formatting rules
dart_style:
  indent_size: 2
  newline_before_members: true
  trailing_comma: false
  preserve_closing_brace_indentation: true

linter:
  rules:
    avoid_print: false
    prefer_const_constructors_in_immutables: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_final_fields: false
    unnecessary_breaks: true
    use_key_in_widget_constructors: false
