name: bleya

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  provider: ^6.0.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  cloud_functions: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
